"""include auth fastapiusers fix

Revision ID: 64ddd39f1ab8
Revises: 1c9dc7e90ac1
Create Date: 2023-05-31 23:33:47.873111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ddd39f1ab8'
down_revision = '1c9dc7e90ac1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
